Polished grammar, spelling, and formatting of Documentation
Bubka/2FAuth-Docs pull request #2
Opened 2022-06-04 06:37 UTC by Blake192

2022-06-13 09:09 UTC, Bubka requested changes
Great review, thank you very much! My English still has to be improved.

Please just restore _Self-hosted_ in place of _Bare-metal_ (see related comment).

2022-06-13 09:09 UTC, Bubka commented on docs/getting-started/installation/bare-metal.md
> +# Bare-metal
Please restore the Self-hosted term. Bare-metal is too restrictive whereas Self-hosted is commonly used.

2022-06-23 17:32 UTC, Blake192 commented on docs/getting-started/installation/bare-metal.md
> +# Bare-metal
Fixed with latest commit

2022-06-23 17:35 UTC, Blake192 commented
Another thing I changed in this PR was giving the `docker-compose.yml` file its own section to allow people to dive into the project faster (kind trying to mimic how linuxserver.io does it). It would be smart to assign a github action to update the Docker-Compose section of the documentation with the file every time the file is changed for efficiency.

2022-07-07 19:20 UTC, Bubka approved these changes

2022-07-07 19:22 UTC, merged